pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    stages {
        stage ('init') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh '''
                            cd 10-sg
                            terraform init
                        '''
                    }
                }
            }
        }
        stage ('plan') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh '''
                            cd 10-sg
                            terraform plan
                        '''
                    }
                }
            }
        }
        stage ('apply') {
            steps {
                input (
                    message: 'Do you want to apply the changes?',
                    ok: 'Apply'
                )
                script {
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh '''
                            cd 10-sg
                            terraform apply -auto-approve
                        '''
                    }
                }
            }
        }        
    }
    post {
        always {
            cleanws()
        }
    }
}