pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    stages {
        stage ('init') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh '''
                            pwd
                            ls -l
                            cd 10-sg
                            terraform init
                        '''
                    }
                }
            }
        }
        stage ('plan') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh '''
                            cd 10-sg
                            terraform plan
                        '''
                    }
                }
            }
        }
        stage ('apply') {
            steps {
                // input (
                //     message: 'Do you want to apply the changes?',
                //     ok: 'Apply'
                // )
                script {
                    withAWS(region:'us-east-1',credentials:'aws-auth') {
                        sh '''
                            cd 10-sg
                            terraform apply -auto-approve
                        '''
                    }
                }
            }
        }
        stage ('Parallel stages') {
            parallel { 
                stage ('sg rules') {
                    steps {
                        script {
                            builld job: '30-sg-rules',
                            wait: false,  
                            propagate: false
                        }
                    }
                }
                stage ('Bastion') {
                    steps {
                        script {
                            build job: '20-bastion',
                            wait: false,  
                            propagate: false
                        }
                    }
                }
                stage ('ACM') {
                    steps {
                        script {
                            build job: '70-ACM',
                            wait: false,  
                            propagate: false
                        }
                    }
                }
                
                stage ('EKS') {
                    steps {
                        script {
                            build job: '90-eks',
                            wait: false,  
                            propagate: false
                        }
                    }
                }
                stage ('ECR') {
                    steps {
                        script {
                            build job: '40-ecr',
                            wait: false,  
                            propagate: false
                        }
                    }
                }
            
            }
        }
        stage ('ALB') {
            steps {
                script {
                    build job: '80-ingress-alb',
                    wait: false,  
                    propagate: false 
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}