pipeline {
    agent {
        node {
            label 'agent-1'
        }
    }
    stages {
        stage ('init') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-auth') {
                    sh '''
                        cd 80-ingress-alb
                        terraform init
                    '''
                }
                    
            }
        }
        stage ('plan') {
            steps {
                withAWS(region:'us-east-1',credentials:'aws-auth') {
                    sh '''
                         cd 80-ingress-alb
                         terraform plan
                    '''
                }  
            }
        }
        stage ('apply') {
            steps {
                // input (
                //     message: 'Do you want to apply the changes?',
                //     ok: 'Apply'
                // )
                withAWS(region:'us-east-1',credentials:'aws-auth') {
                    sh '''
                        cd 80-ingress-alb
                        terraform apply -auto-approve
                    '''
                }
            }
        }
    }
    post {
        always {
            echo "cleaning up workspace ..."
            cleanWs()
        }
    }
}